import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AnimatePresence, motion, useMotionValue, useReducedMotion, useSpring, useTransform } from 'framer-motion';
import { BriefcaseBusiness as Linkedin, Code2 as Github, ExternalLink, Mail, MapPin, Phone, Send } from 'lucide-react';
import '../styles.css';
import Navbar from './components/Navbar';

const projects = [
  { number: '01', title: 'ResumeIQ', copy: 'AI resume intelligence platform that evaluates ATS compatibility, matches candidates to roles, and turns skill gaps into an actionable next step.', tags: ['Next.js', 'FastAPI', 'Groq', 'MongoDB', 'pgvector'], demo: 'https://frontend-liard-phi-22.vercel.app/', github: 'https://github.com/gayathri1011/ResumeIQ.git', image: '/projects/Screenshot 2026-08-27 114744.png' },
  { number: '02', title: 'SpendWise', copy: 'Subscription optimizer tracking recurring expenses, upcoming payments, and low-usage services to surface potential savings.', tags: ['Python', 'FastAPI', 'SQLite', 'REST API'], demo: 'https://spendwise-subscription-optimizer-i3.vercel.app/', github: 'https://github.com/gayathri1011/spendwise-subscription-optimizer.git', image: '/projects/Screenshot 2026-09-11 151057.png' },
  { number: '03', title: 'TravelGo', copy: 'Responsive travel booking experience for exploring destinations, comparing packages, and planning the next escape.', tags: ['HTML', 'CSS', 'JavaScript', 'Git'], demo: 'https://travel-go-ochre.vercel.app/', github: 'https://github.com/gayathri1011/TravelGo.git', image: '/projects/Screenshot 2026-09-11 161727.png' },
];
const skills = [['Languages', 'Python · JavaScript · TypeScript · SQL · Java · HTML · CSS'], ['AI / ML', 'Machine Learning · NLP · Generative AI · Scikit-learn · XGBoost · RAG · Groq'], ['Web & Backend', 'React.js · Next.js · Node.js · FastAPI · REST API · Tailwind CSS'], ['Cloud & Data', 'AWS · S3 · Lambda · DynamoDB · Bedrock · MongoDB · PostgreSQL · SQLite · Firebase'], ['Tools', 'Git · GitHub · Docker · Pandas · PyMuPDF · pgvector · Vercel · Render']];
const experience = [['JUL — AUG 2026', 'Data Analyst Intern', 'Eagle-HiTech Softcloud Pvt Ltd · Chennai', 'Analyzed business datasets using Excel and Python, building dashboards that streamlined recurring reporting.'], ['JAN — MAR 2026', 'AWS Cloud Computing Virtual Intern', 'NASSCOM · Virtual', 'Completed hands-on work with EC2, S3, and Lambda while learning cloud architecture fundamentals.'], ['JAN — MAR 2026', 'AI-ML Virtual Intern', 'EduSkills Academy · Virtual', 'Built and trained machine learning models for applied problem statements and real-world case studies.'], ['JUL — AUG 2025', 'Data Science Intern', 'Phoenix SoftTech · Madurai', 'Performed statistical analysis and assisted in building and evaluating predictive models.']];
const certifications = ['AWS Certified AI Practitioner', 'AWS Cloud Quest — Cloud Practitioner', 'IBM — Getting Started with Artificial Intelligence', 'Infosys — Foundation Course in Machine Learning'];

function Reveal({ children, className = '', delay = 0 }) { const reduceMotion = useReducedMotion(); return <motion.div className={className} initial={reduceMotion ? { opacity: 0 } : { opacity: 0, y: 34, z: -35 }} whileInView={reduceMotion ? { opacity: 1 } : { opacity: 1, y: 0, z: 0 }} viewport={{ once: true, amount: .15 }} transition={{ duration: .65, delay, ease: [.22, .8, .25, 1] }} style={{ transformPerspective: 900, transformStyle: 'preserve-3d' }}>{children}</motion.div>; }
function SectionMotion({ children, className, id }) { const reduceMotion = useReducedMotion(); return <motion.section id={id} className={className} initial={reduceMotion ? { opacity: 0 } : { opacity: 0, y: 55, z: -45 }} whileInView={reduceMotion ? { opacity: 1 } : { opacity: 1, y: 0, z: 0 }} viewport={{ once: true, amount: .08 }} transition={{ duration: .8, ease: [.22, .8, .25, 1] }} style={{ transformPerspective: 1200, transformStyle: 'preserve-3d' }}>{children}</motion.section>; }
function SectionIntro({ number, label, title, copy }) { const isPageTwo = number === '01'; return <div className="section-intro"><motion.span className="eyebrow section-number" initial={{ opacity: 0, y: isPageTwo ? -100 : -28, rotateX: isPageTwo ? -90 : -55 }} whileInView={{ opacity: 1, y: 0, rotateX: 0 }} viewport={{ once: true, amount: .35 }} transition={{ type: 'spring', stiffness: isPageTwo ? 145 : 180, damping: isPageTwo ? 13 : 16 }}>{number} — {label}</motion.span><h2>{title}</h2>{copy && <p>{copy}</p>}</div>; }
function HeroVisual() { const x = useMotionValue(0); const y = useMotionValue(0); const sx = useSpring(x, { stiffness: 90, damping: 20 }); const sy = useSpring(y, { stiffness: 90, damping: 20 }); const rx = useTransform(sy, [-10, 10], [8, -8]); const ry = useTransform(sx, [-10, 10], [-10, 10]); return <motion.div className="hero-visual" onPointerMove={(e) => { const r = e.currentTarget.getBoundingClientRect(); x.set(((e.clientX - r.left) / r.width - .5) * 10); y.set(((e.clientY - r.top) / r.height - .5) * 10); }} onPointerLeave={() => { x.set(0); y.set(0); }} style={{ rotateX: rx, rotateY: ry }}><div className="visual-grid" /><motion.div className="visual-ring ring-one" animate={{ rotateZ: 360 }} transformTemplate={({ rotateZ }) => `rotate(-28deg) rotateX(15deg) rotateZ(${rotateZ})`} transition={{ duration: 22, repeat: Infinity, ease: 'linear' }} /><motion.div className="visual-ring ring-two" animate={{ rotateZ: -360 }} transformTemplate={({ rotateZ }) => `rotate(58deg) rotateZ(${rotateZ})`} transition={{ duration: 30, repeat: Infinity, ease: 'linear' }} /><div className="visual-label"><b>∞</b><span>AI · DATA</span></div></motion.div>; }
function ProjectCarousel() { const [index, setIndex] = useState(0); const reduceMotion = useReducedMotion(); const lastEdgeChange = useRef(0); const project = projects[index]; const change = (direction) => setIndex((current) => (current + direction + projects.length) % projects.length); const handlePointerMove = (event) => { if (reduceMotion) return; const bounds = event.currentTarget.getBoundingClientRect(); const edgeSize = Math.min(120, bounds.width * .16); const nearRight = event.clientX > bounds.right - edgeSize; const nearLeft = event.clientX < bounds.left + edgeSize; const now = Date.now(); if ((nearRight || nearLeft) && now - lastEdgeChange.current > 850) { change(nearRight ? 1 : -1); lastEdgeChange.current = now; } }; return <><div className="project-carousel" onPointerMove={handlePointerMove}><div className="carousel-stage"><AnimatePresence mode="wait" initial={false}><motion.article key={project.number} className="carousel-card" drag={reduceMotion ? false : 'x'} dragConstraints={{ left: 0, right: 0 }} dragElastic={.16} onDragEnd={(_, info) => { if (info.offset.x < -70) change(1); if (info.offset.x > 70) change(-1); }} initial={{ opacity: 0, x: reduceMotion ? 0 : 90, z: -60 }} animate={{ opacity: 1, x: 0, z: 0 }} exit={{ opacity: 0, x: -90, z: -60 }} transition={{ duration: .42, ease: [.22, .8, .25, 1] }}><div className="project-preview"><img src={project.image} alt={`${project.title} project preview`} /></div><div className="carousel-copy"><div className="project-card-top"><span>{project.number} / 03</span><span>LIVE PROJECT</span></div><h3>{project.title}</h3><p>{project.copy}</p><div className="tags">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><div className="project-actions"><a className="button filled" href={project.demo} target="_blank" rel="noreferrer">Live Demo <span>↗</span></a><a className="button text-button" href={project.github} target="_blank" rel="noreferrer">GitHub <span>↗</span></a></div></div></motion.article></AnimatePresence></div><div className="carousel-controls"><button type="button" onClick={() => change(-1)} aria-label="Previous project">←</button><div className="carousel-dots">{projects.map((item, itemIndex) => <button type="button" className={itemIndex === index ? 'active' : ''} onClick={() => setIndex(itemIndex)} aria-label={`Show ${item.title}`} key={item.number} />)}</div><button type="button" onClick={() => change(1)} aria-label="Next project">→</button><span>{String(index + 1).padStart(2, '0')} / {String(projects.length).padStart(2, '0')}</span></div></div></>;
}
function PageMotion({ children }) { const reduceMotion = useReducedMotion(); const x = useMotionValue(0); const depth = useSpring(useTransform(x, [-1, 1], [-6, 6]), { stiffness: 80, damping: 24 }); return <motion.main className="page-stage" onPointerMove={reduceMotion ? undefined : (event) => { x.set((event.clientX / window.innerWidth - .5) * 2); }} onPointerLeave={() => x.set(0)} style={reduceMotion ? undefined : { z: depth, transformPerspective: 1800, transformStyle: 'preserve-3d' }}>{children}</motion.main>; }
function AnimatedCursor() { const reduceMotion = useReducedMotion(); const x = useMotionValue(-20); const y = useMotionValue(-20); const ringX = useSpring(x, { stiffness: 180, damping: 22 }); const ringY = useSpring(y, { stiffness: 180, damping: 22 }); useEffect(() => { if (reduceMotion) return undefined; const moveCursor = (event) => { x.set(event.clientX); y.set(event.clientY); }; window.addEventListener('pointermove', moveCursor); return () => window.removeEventListener('pointermove', moveCursor); }, [reduceMotion, x, y]); return <><motion.span className="cursor-core" style={reduceMotion ? undefined : { x, y }} /><motion.span className="cursor-ring" style={reduceMotion ? undefined : { x: ringX, y: ringY }} /></>; }
function App() { return <div className="site-shell"><AnimatedCursor /><Navbar /><PageMotion>
  <section className="hero" id="hero"><div className="hero-inner"><div className="hero-copy"><Reveal><span className="eyebrow">AI & DATA SCIENCE</span><h1>R.S. Gayathri</h1><h3>Turning data into<br /><em>meaningful systems.</em></h3><p className="hero-lead">I build intelligent applications, full-stack products, and cloud-based systems that turn ideas into useful experiences.</p><div className="hero-actions"><a className="button filled" href="#projects">Explore my work <ExternalLink aria-hidden="true" size={15} /></a><a className="button text-button" href="./Gayathri_RS_Resume.pdf" target="_blank" rel="noreferrer">Download resume <ExternalLink aria-hidden="true" size={15} /></a></div><div className="socials"><a href="https://github.com/gayathri1011" target="_blank" rel="noreferrer" aria-label="GitHub"><Github aria-hidden="true" size={17} /> <span>GitHub</span></a><a href="https://www.linkedin.com/in/gayathri10" target="_blank" rel="noreferrer" aria-label="LinkedIn"><Linkedin aria-hidden="true" size={17} /> <span>LinkedIn</span></a><a href="mailto:gayathri.r.s.10e@gmail.com" aria-label="Email"><Mail aria-hidden="true" size={17} /> <span>Email</span></a></div></Reveal></div><Reveal className="hero-art" delay={.18}><HeroVisual /></Reveal></div><div className="scroll-cue"><span>SCROLL TO EXPLORE</span><i /></div></section>
  <SectionMotion className="content-section about-section" id="about"><SectionIntro number="01" label="About me" title={<>Turning ideas into<br /><em>intelligent solutions.</em></>} /><div className="about-grid"><Reveal><p className="large-copy">I'm Gayathri, an AI & Data Science student who enjoys turning ideas into real, usable technology.</p><p>I work across AI, Machine Learning, Full-Stack Development, and AWS Cloud — building projects that combine intelligent systems, thoughtful design, and practical functionality.</p><p>I believe the best way to learn technology is to build with it: experimenting, solving problems, breaking things, and finding ways to build better.</p></Reveal><Reveal className="stat-grid" delay={.12}>{[['04', 'Projects'], ['04', 'Internships'], ['8.20', 'CGPA'], ['04', 'Certifications']].map(([v, l]) => <div className="stat" key={l}><strong>{v}</strong><span>{l}</span></div>)}</Reveal></div></SectionMotion>
  <SectionMotion className="content-section projects-section" id="projects"><SectionIntro number="02" label="Projects" title={<>Where innovation meets<br /><em>real-world impact.</em></>} copy="Swipe through selected builds across AI, web, data, and cloud." /><ProjectCarousel /></SectionMotion>
  <SectionMotion className="content-section skills-section" id="skills"><SectionIntro number="03" label="Skills" title={<>The tools and technologies<br /><em>I build with.</em></>} copy="From model training to full-stack delivery and cloud deploy." /><div className="skill-list">{skills.map(([name, items], i) => <Reveal key={name} delay={i * .06}><div className="skill-row"><span>0{i + 1}</span><h3>{name}</h3><p>{items}</p></div></Reveal>)}</div></SectionMotion>
  <SectionMotion className="content-section experience-section" id="experience"><SectionIntro number="04" label="Experience" title={<>Progress powered by<br /><em>practical learning.</em></>} copy="Hands-on data analysis, cloud computing, and applied AI/ML experience." /><div className="timeline">{experience.map(([date, role, company, copy], i) => <Reveal key={role} delay={i * .06}><article className="timeline-row"><span className="timeline-date">{date}</span><div><h3>{role}</h3><p className="company">{company}</p><p>{copy}</p></div></article></Reveal>)}</div></SectionMotion>
  <SectionMotion className="content-section education-section" id="education"><SectionIntro number="05" label="Education" title={<>Learning with<br /><em>purpose.</em></>} copy="Building a strong foundation in AI, data, and software engineering." /><Reveal className="education-card"><div><span className="eyebrow">2023 — 2027</span><h3>B.Tech in Artificial Intelligence & Data Science</h3><p>SSM Institute of Engineering and Technology · Dindigul, Tamil Nadu</p></div><strong>8.20 <small>CGPA</small></strong></Reveal></SectionMotion>
  <SectionMotion className="content-section cert-section" id="certifications"><SectionIntro number="06" label="Certifications" title={<>Proof of skills, backed by<br /><em>real credentials.</em></>} /><div className="cert-grid">{certifications.map((cert, i) => <Reveal key={cert} delay={i * .06}><article><span>0{i + 1}</span><h3>{cert}</h3><p>{i < 2 ? 'Amazon Web Services' : i === 2 ? 'IBM' : 'Infosys'}</p></article></Reveal>)}</div></SectionMotion>
  <SectionMotion className="contact-section" id="contact"><div className="contact-heading"><span className="eyebrow">06 — CONTACT</span><h2>Let's build <em>something</em><br /><em>together.</em></h2><p>Open to AI/ML, full-stack, and cloud opportunities. Reach out anytime.</p><div className="contact-details"><a href="mailto:gayathri.r.s.10e@gmail.com"><span><Mail aria-hidden="true" size={13} /> EMAIL</span><strong>gayathri.r.s.10e@gmail.com</strong></a><a href="tel:+917530004846"><span><Phone aria-hidden="true" size={13} /> PHONE</span><strong>+91 75300 4846</strong></a><span><span><MapPin aria-hidden="true" size={13} /> LOCATION</span><strong>Dindigul, Tamil Nadu</strong></span><a href="https://github.com/gayathri1011" target="_blank" rel="noreferrer"><span><Github aria-hidden="true" size={13} /> GITHUB</span><strong>github.com/gayathri1011</strong></a><a href="https://www.linkedin.com/in/gayathri10" target="_blank" rel="noreferrer"><span><Linkedin aria-hidden="true" size={13} /> LINKEDIN</span><strong>linkedin.com/in/gayathri10</strong></a></div></div><form className="contact-form" onSubmit={(event) => event.preventDefault()}><label htmlFor="contact-name">Name</label><input id="contact-name" name="name" placeholder="Your name" required /><label htmlFor="contact-email">Email</label><input id="contact-email" type="email" name="email" placeholder="you@email.com" required /><label htmlFor="contact-message">Message</label><textarea id="contact-message" name="message" placeholder="Tell me about the role, project, or idea..." rows="5" required /><button className="button filled" type="submit">Send message <Send aria-hidden="true" size={15} /></button></form></SectionMotion>
 </PageMotion><footer><span>RG / AI & DATA SCIENCE</span><span>BUILD · LEARN · SHIP · REPEAT</span><span>© 2026</span></footer></div>; }
createRoot(document.getElementById('root')).render(<App />);
